global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pubsub'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['pubsub:2112']
    honor_labels: true
    scrape_timeout: 4s
    metrics_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        action: keep
